### ISSUE TITLE
Slow EventBus

### ISSUE THREAD

**Issue by einrobin** [FlintMC/FlintMC#68]
**Is your feature request related to a problem? Please describe.**
Currently the EventBus discovers all SubscribeMethods when an event is being fired, obviously this process is pretty time-consuming and should be moved to the startup.

**Describe the solution you'd like**
Maybe we could generate a class that holds a collection with all SubscribeMethods per event.
#11 could help discovering all events.

**Comment by zortax** [comment]
We could also scan for the call that is actually firing the event and replace it with a call that calls a generated executor that holds a list of listeners for that event. This would reduce worst case time complexity to O(1) (instead of O(log n) if the listeners are saved in a map)

**Comment by einrobin** [comment]
I don't think that this would be a good idea, some calls to the fireEvent method are also generated. I thought about adding a list of listeners to the class of the event, but this wouldn't work if the event is an interface.

**Comment by zortax** [comment]
You could use default methods tho

**Comment by zortax** [comment]
You could use default methods tho

**Comment by zortax** [comment]
You could use default methods tho
