### ISSUE TITLE
Improve Package Loader

### ISSUE THREAD

**Issue by zortax** [FlintMC/FlintMC#95]
There are some things that need to be done:
- [x] Refactor package loading (into a more responsibility driven approach)
- [x] Fix bugs in  package loading
- [x] implement a better algorithm for dependency resolution (find best loadable dep. graph)

**Comment by Janrupf** [comment]
Please consider implementing at least a basic support for unloading - it doesn't have to be functional yet, but just be there so it can get implemented eventually.

**Comment by zortax** [comment]
unloading is pretty much impossible to implement for packages that use class transformations or anything alike. To properly implement unloading for the other APIs, significant changes in the Service API would be necessary. Proposed architecture would be to differ between `ServiceHandler` and `UnloadableServiceHandler` which would then also implement a method to unload a discovered annotation; I could then automatically blacklist packages with one or more annotation discovered by a not unloadable service handler from being unloaded, though this would make it incredibly nontransparent for package authors wether their package is gonna be unloadable. And even if a package should be unloadable by itself, the unloading could be blocked as it could potentially break the dependency graph. The problem gets even more complicated when considering that packages can contain service handlers as well.

So unloading is
- difficult to implement for packages that only depend on the minecraft API
- even more difficult for packages that use class transformation APIs
- pretty much impossible to implement for packages using javassist/ow2 ASM (unless we use instrumentation/hotswapping which I wouldn't)
- nontransparent and difficult to understand for package authors and users

That's why I personally would not implement unloading at all and I am certainly not gonna do it right now.
We can however talk about a "disabling" API, which optionally allows packages to be disabled. The package won't be unloaded, event listeners etc. would still be registered, the responsibility would be with the package author to just "disable" all package logic. The package author could then decide whether it can be disabled by the user.
